### ISSUE TITLE
Metanorma XML for PLATEAU

### ISSUE THREAD

**Issue by strogonoff** [metanorma/firelight#8]
Is it possible to have a sample?

**Comment by opoudjis** [comment]
https://github.com/metanorma/mn-samples-plateau/

Compile that following the instructions in the README.

Currently apparently this Firelight thing is set up to read Semantic XML (*.xml). That was a stupid design decision, taken by people who don't talk to me and do not know what they are doing. It should be consuming Presentation XML (*.presentation.xml), which resolves numbering, does i18n, and orders clauses. As it turns out, the Presentation XML embeds the Semantic XML at the beginning anyway (`semantic_` prefixed to all elements and anchors with equivalents in the Presentation XML.)

**Comment by strogonoff** [comment]
In my process issues are usually closed by the callers when truly resolved (i.e., I need XML => You help me obtain it => I close the issue when it’s all good), but as long as this is under MN org I guess when in Rome…

**Comment by ronaldtse** [comment]
I agree with @strogonoff . Issues should only be closed when resolved. But I know @opoudjis uses a different understanding of “resolved” for colleagues vs clients 🤣
